apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS EdgeCPS;
    
    USE EdgeCPS;


  # CREATE TABLE `TB_GROUP` (
  # `GROUP_IDX` bigint(20) NOT NULL AUTO_INCREMENT,
  # `GROUP_NAME` varchar(100) NOT NULL,
  # `GROUP_CODE` varchar(100) NOT NULL,
  # PRIMARY KEY (`GROUP_IDX`));

  # INSERT INTO `TB_GROUP` VALUES (999,'admin_group','AG');


  # CREATE TABLE `TB_PROCESS` (
  # `PROC_IDX` bigint(20) NOT NULL AUTO_INCREMENT,
  # `PROJ_IDX` bigint(20) NOT NULL,
  # `PROC_NAME` varchar(100) NOT NULL,
  # `PROC_XML` varchar(100) NOT NULL,
  # `PROC_DICT` varchar(100) NOT NULL,
  # PRIMARY KEY (`PROC_IDX`),
  # KEY `TB_PROCESS_FK` (`PROJ_IDX`),
  # CONSTRAINT `TB_PROCESS_FK` FOREIGN KEY (`PROJ_IDX`) REFERENCES `TB_PROJ` (`PROJ_IDX`)); 


  # CREATE TABLE `TB_PROJ` (
  # `PROJ_IDX` bigint(20) NOT NULL AUTO_INCREMENT,
  # `PROJ_NAME` varchar(100) NOT NULL,
  # `PROJ_CREATE_DATE` varchar(100) NOT NULL,
  # `USER_IDX` bigint(20) NOT NULL,
  # PRIMARY KEY (`PROJ_IDX`),
  # KEY `TB_PROJ_FK` (`USER_IDX`),
  # CONSTRAINT `TB_PROJ_FK` FOREIGN KEY (`USER_IDX`) REFERENCES `TB_USER` (`USER_IDX`)); 


  # CREATE TABLE `TB_USER` (
  # `USER_IDX` bigint(20) NOT NULL AUTO_INCREMENT,
  # `USER_ID` varchar(100) NOT NULL,
  # `USER_NAME` varchar(100) NOT NULL,
  # `USER_PWD` varchar(100) NOT NULL,
  # `USER_EMAIL` varchar(100) NOT NULL,
  # `GROUP_IDX` bigint(20) NOT NULL,
  # PRIMARY KEY (`USER_IDX`),
  # KEY `TB_USER_FK` (`GROUP_IDX`),
  # CONSTRAINT `TB_USER_FK` FOREIGN KEY (`GROUP_IDX`) REFERENCES `TB_GROUP` (`GROUP_IDX`));

  # INSERT INTO `TB_USER` VALUES (9999,'USR','KPST','1111','kpst@kpst.co.kr',999);