apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: mariadb-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi