apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume 
  labels:
    type: local
spec:
  storageClassName: mariadb-storage-class
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/kpst/Desktop/EdgeCPS/Edgecps/edgeCpsProject/db/data"